[env:emisor_mando]
platform = atmelavr
board = nanoatmega328
framework = arduino

; Si al subir el código te da error, cambia la línea de 'board' por:
; board = nanoatmega328new

lib_deps =
    tmrh20/RF24 @ ^1.4.7

monitor_speed = 9600